// ! MANTENER ACCIONES ORDENADAS POR TIPO, Y LUEGO POR ORDEN ALFABÉTICO

// * ANIMO DE ALBERTO
export const ANIMO_INCREMENTAR = 'ANIMO_INCREMENTAR';
export const ANIMO_REDUCIR = 'ANIMO_REDUCIR';

// * CHARLA
export const CHARLA_AGREGAR_NUEVO_MENSAJE_AL_HISTORIAL = 'CHARLA_AGREGAR_NUEVO_MENSAJE_AL_HISTORIAL';
export const CHARLA_USUARIE_ENVIO_MENSAJE = 'CHARLA_USUARIE_ENVIO_MENSAJE';
export const CHARLA_ESTABLECER_CONTEXTO_GENERO_MASCULINO = 'CHARLA_ESTABLECER_CONTEXTO_GENERO_MASCULINO';
export const CHARLA_ESTABLECER_CONTEXTO_GENERO_FEMENINO = 'CHARLA_ESTABLECER_CONTEXTO_GENERO_FEMENINO';


// * CLIENTE
export const CLIENTE_MODIFICAR_ALTO_DISPONIBLE = 'CLIENTE_MODIFICAR_ALTO_DISPONIBLE';
export const CLIENTE_MODIFICAR_ANCHO_DISPONIBLE = 'CLIENTE_MODIFICAR_ANCHO_DISPONIBLE';

// * ESTADO DE ALBERTO
export const ESTADO_ESTABLECER_ALBERTO_CONECTADO = 'ESTADO_ESTABLECER_ALBERTO_CONECTADO';
export const ESTADO_ESTABLECER_ALBERTO_DESCONECTADO = 'ESTADO_ESTABLECER_ALBERTO_DESCONECTADO';
export const ESTADO_ESTABLECER_ALBERTO_ESCRIBIENDO = 'ESTADO_ESTABLECER_ESCRIBIENDO';

// * GENERAL
export const GENERAL_ALTERNAR_CONSENTIMIENTO_DE_COLABORACION = 'GENERAL_ALTERNAR_CONSENTIMIENTO_DE_COLABORACION';
export const GENERAL_ESTABLECER_SESSION_ID = 'GENERAL_ESTABLECER_SESSION_ID';
export const GENERAL_MARCAR_CHARLA_COMENZADA = 'GENERAL_MARCAR_CHARLA_COMENZADA';
export const GENERAL_MARCAR_CHARLA_TERMINADA = 'GENERAL_MARCAR_CHARLA_TERMINADA';
export const GENERAL_SELECCIONAR_GENERO = 'GENERAL_SELECCIONAR_GENERO';
